#!/bin/bash

echo "Ensure that the  root keys are presents..."
curl -L "${ETCD_HOST}/v2/keys/services?dir=true" -XPUT
curl -L "${ETCD_HOST}/v2/keys/apps?dir=true" -XPUT

echo "Starting supervisord..."
supervisord -n
